include:
    - server-services/service-icap-compose.yaml
    - server-services/service-layer3-compose.yaml
    - server-services/utility-webserver-compose.yaml

networks:
  default:
    driver: bridge

  webserver-net:
    driver: macvlan
    driver_opts:
      parent: ens6.80
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
